# docker-compose.yml
version: '3.8'
services:
  ner_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    volumes:
      - /home/aime/.cache/huggingface/hub/models--tsmatz--xlm-roberta-ner-japanese/snapshots/39c525b11d35426fea754e906c4847208582647f:/app/model
    ports:
      - 7000:7000
