version: '3'
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile_1
    ports:
      - "7000:7000" 
    depends_on:
      - service2

  service2:
    build:
      context: .
      dockerfile: Dockerfile_2
    ports:
      - "7010:7010"
