version: '3'
services:
  middle:
    build:
      context: .
      dockerfile: Dockerfile_1
      args:
        PORT: ${MIDDLE_CONTAINER_PORT}
    ports:
      - "${MIDDLE_HOST_PORT}:${MIDDLE_CONTAINER_PORT}"
    depends_on:
      - endpoint
    env_file:
      - .env
    networks:
      - backend
  endpoint:
    build:
      context: .
      dockerfile: Dockerfile_2
      args:
        PORT: ${ENDPOINT_CONTAINER_PORT}
    ports:
      - "${ENDPOINT_HOST_PORT}:${ENDPOINT_CONTAINER_PORT}"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
