FROM python:3.9-slim

WORKDIR /app
COPY . /app
RUN pip install fastapi uvicorn requests

ARG PORT=7000 
ENV PORT=$PORT

EXPOSE $PORT

CMD ["sh", "-c", "uvicorn middle:app --host 0.0.0.0 --port $PORT"]
