version: '3'
services:
  middle:
    build:
      context: .
      dockerfile: Dockerfile_1
    ports:
      - "7000:7000"
    depends_on:
      - endpoint

  endpoint:
    build:
      context: .
      dockerfile: Dockerfile_2
    ports:
      - "7010:7010"
