FROM python:3.9-slim
WORKDIR /app
COPY . /app
RUN pip install fastapi uvicorn requests

ARG PORT=7010 
ENV PORT=$PORT

EXPOSE $PORT

CMD ["sh", "-c", "uvicorn endpoint:app --host 0.0.0.0 --port $PORT"]
